services:
  backend:
    build: ./qrest-backend
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - db

  frontend:
    build: ./qrest-frontend
    ports:
      - "4200:80"
    env_file:
      - .env
    depends_on:
      - backend
    volumes:
      - ./qrest-frontend/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: qrestdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

